### ISSUE TITLE
Please update the package

### ISSUE THREAD

**Issue by arafath-mk** [dontpanic92/wxGo#1]
This is a nice library. Please update this library with the latest version of Go and wxWidgets.

**Comment by dontpanic92** [comment]
Thanks for your comment. I haven't paid much attention to golang for a long time, so I have to look through some latest materials about golang first. 

I googled about gui toolkit on golang and only found few usable packages which are all with some limits, six years after golang's v1.0. Perhaps golang isn't a good choice for GUI applications, which is indeed not the objective of golang's design.

However, I will try to make this project alive again, since we really don't have many choices if we decided to make a GUI app :smile: . You can have a look at https://github.com/lxn/walk and https://github.com/andlabs/ui if you want a gui library immediately.

**Comment by arafath-mk** [comment]
@dontpanic92 Thanks for the reply. I prefer wxGo over other libraries because, wxWidgets is stable and an active community is there.
