### ISSUE TITLE
Certain controls crash(?) wxGo application

### ISSUE THREAD

**Issue by axelniedenhoff** [dontpanic92/wxGo#17]
I have found that using certain controls (TreeListCtrl and WebView in particular) makes a wxGo application simply exit without displaying anything. Now I don’t know whether I am doing anything wrong (some missing initialization before using such controls, perhaps?) or whether these controls are just not yet supported or whether we have a bug in wxGo on our hands. I am testing under Windows 7 64-bit with Go 1.7.4. Here is a sample program that is supposed to show a frame with at least a bit of TreeListCtrl in it, but which simply shows nothing and exits:

`package main

import "github.com/dontpanic92/wxGo/wx"

func main() {
	app := wx.NewApp()
	frame := wx.NewFrame(wx.NullWindow, -1, "Hello, world!")
	sizer := wx.NewBoxSizer(wx.VERTICAL)
	tlc := wx.NewTreeListCtrl(frame)
	sizer.Add(tlc, 0, wx.ALL|wx.EXPAND, 5)
	frame.SetSizer(sizer)
	frame.Layout()
	frame.Show()
	app.MainLoop()
}
`

(The preview does not show the code nicely, but I do hope it will be better in the actual post.)

**Comment by dontpanic92** [comment]
Hi,

Sorry for the late response. The crashing is caused by wrong parameter you passed into `wx.NewTreeListCtrl`. In http://docs.wxwidgets.org/3.1/classwx_tree_list_ctrl.html we can see that it has 2 overloaded functions, one is receiving no parameter while the other is receiving 2 parameters. 

So, `tlc := wx.NewTreeListCtrl(frame, wx.ID_ANY)` will work.

Thanks

**Comment by axelniedenhoff** [comment]
You are right, of course. I missed the fact that the second argument is mandatory. Sorry! And thank you for having a look!
