### ISSUE TITLE
wx.Swiglscolour wx.WHITE

### ISSUE THREAD

**Issue by adva-cg** [dontpanic92/wxGo#25]
I use code "SetBackgroundColour(wx.WHITE)".
Error is "wx.WHITE - undefined".
What are the values of type wx.Gwiglscolour?

**Comment by adva-cg** [comment]
Replace by "wx.GetWHITE()". It works.

**Comment by dontpanic92** [comment]
:+1: 

The reason that we have to use a function instead of a variable/constant is that these C++ macros (WHITE, BLACK, etc.) are actually function calls. It will crash if we call these functions before wxWidgets gets ready..

The `SwigIsABC` type is a interface that indicates this type is `wxABC`. We need these types due to the different design between Go and C++. In C++, there is a mechanism called name-hiding. For example,

```C++
// C++
class Base {
public:
void A();
};

class Derived : public Base {
public:
void A(int a); // Base::A is hidden.
};
```

However, in Go it will makes `Derived` not implement the parent's interface:

```go
type Base interface {
A()
}
// type Base struct ...
func (p *base) A() { ... }
// type Derived struct ...
func (p *derived) A(int a) {...}

func someFuncThatUseBase(Base b) {...}
d = &Derived{}
someFuncThatUseBase(d) // Wrong
// Derived doesn't match the Base interface!
```

So the solution is that introducing another interface, which is just used for recognizing the real type of a structure:

```
type BaseType interface {
    IAmBase()  // Make sure that base and all of its children implement this interface
}
```

And every where we need a `Base` parameter, we replace it with `BaseInterface`. This solves the issue.

In wxWidgets, `wxTreeCtrl` has a function called `GetNextSibling`, so as `wxWindow`. Their parameters are different, so in Go `wx.TreeCtrl` will not match the `wx.Window` interface, and we cannot pass a `wx.TreeCtrl` to any function that receives `wx.Window` as a parameter.

**Comment by adva-cg** [comment]
I don't found method `ToDocMDIParentFrame` in wxWidgets. This is from the code 

> subFrame := wx.NewDocMDIChildFrame(document, self.view, wx.ToDocMDIParentFrame(wx.AppGetInstance().GetTopWindow()), wx.ID_ANY, "Child Frame", wx.DefaultPosition, wx.NewSizeT(300, 300))

Where did this method come from?

**Comment by dontpanic92** [comment]
Actually wx.ToABC is the equavallent of `reinterpret_cast<wxABC*>`
